package com.carlosv.dolaraldia.model.bancos

data class Monitors(
    var airtm: Airtm,
    var amazon_gift_card: AmazonGiftCard,
    var bancamiga: Bancamiga,
    var banco_de_venezuela: BancoDeVenezuela,
    var banco_exterior: BancoExterior,
    var banesco: Banesco,
    var bbva_provincial: BbvaProvincial,
    var bcv: Bcv,
    var binance: Binance,
    var bnc: Bnc,
    var cambios_ra: CambiosRa,
    var dolar_em: DolarEm,
    var dolartoday: Dolartoday,
    var dolartodaybtc: DolartodayBtc,
    var el_dorado: ElDorado,
    var enparalelovzla: Enparalelovzla,
    var italcambio: Italcambio,
    var mercantil: Mercantil,
    var mkambio: Mkambio,
    var monitor_dolar_venezuela: MonitorDolarVenezuela,
    var monitor_dolar_vzla: MonitorDolarVzla,
    var otras_instituciones: OtrasInstituciones,
    var paypal: Paypal,
    var petro: Petro,
    var remesas_zoom: RemesasZoom,
    var skrill: Skrill,
    var syklo: Syklo,
    var yadio: Yadio,
    var zinli: Zinli
)